import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/layout/Header'
import { Separator } from '@/components/ui/separator'
import { Toaster } from 'sonner'
import Footer from '@/components/layout/Footer'
import ProgressbarProvider from '@/components/ProgressbarProvider'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn('bg-background font-sans antialiased', inter.variable)}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div id='web-wrapper' className='container flex min-h-screen flex-col'>
            <Header />
            <Separator className='hidden md:block' />
            <main className='flex-1 pb-20 pt-5 md:pt-10'>
              <ProgressbarProvider>{children}</ProgressbarProvider>
            </main>
            <Toaster position='top-center' closeButton />
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
