import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/theme-provider'
import Header from '@/components/layout/Header'
import { Separator } from '@/components/ui/separator'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'bg-background font-sans antialiased',
          inter.variable,
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div id='web-wrapper' className='min-h-screen container'>
            <Header />
            <Separator className='hidden md:block' />
            <main className='pt-5 md:pt-10 min-h-full'>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
